{"name": "Login failed test", "status": "passed", "steps": [{"name": "Entering incorrect data so that the login fails", "status": "passed", "parameters": [{"name": "username", "value": "'testuser@test.pl'"}, {"name": "password", "value": "'vAb!@#42563gbh&&*'"}], "start": 1669121698323, "stop": 1669121699050}], "attachments": [{"name": "stdout", "source": "fa36eb87-21e3-49c7-807a-707a75ac7c8b-attachment.txt", "type": "text/plain"}], "start": 1669121697172, "stop": 1669121699050, "uuid": "7c3ff8ca-089c-4144-a920-67a4cc014546", "historyId": "97471b02e53f4f2008f686edd919def3", "testCaseId": "11aad89389aef7773ef3ffa94c38d4e7", "fullName": "tests.first_file_test.TestLogIn#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "first_file_test"}, {"name": "subSuite", "value": "TestLogIn"}, {"name": "host", "value": "LAPTOP-EC8GS2UB"}, {"name": "thread", "value": "14844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.first_file_test"}]}